apiVersion: v2
name: kyverno-policies-observability
appVersion: 0.8.1
description: Giant Swarm policies for observability management.
home: https://github.com/giantswarm/kyverno-policies-observability
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
version: 0.8.1
annotations:
  io.giantswarm.application.team: "atlas"
